### PR TITLE
Add package description.

### LINKED ISSUE #23: Add package description to nuget.config
Well this is awkward. We don't have a package description in the current nuget config. We should add that

### PR DESCRIPTION
**Pull request by slagroom**
closes #23

### CODE REVIEW

**Comment by Insomniak47** [comment]
You are legit the worst. Could you also change the authors tag to whatever Guardian's is?

**Comment by slagroom** [comment]
Will do RE authors.

did you want a longer description? TBH I don't think there's much more you could say without constraining the spirit of the lib. Could give examples I guess but same thing really

**Comment by Insomniak47** [comment]
No, no longer description I just thought it was funny that after a year of bugging you the nuget package fix was the first one I saw :P

**Comment by Insomniak47** [comment]
BuMp

**Pull request merged**
